In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
#Loading the dataset
data=pd.read_csv('creditcard.csv',low_memory=False)
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
data.shape

(31780, 31)

In [12]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [16]:
df.dropna()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [13]:
data.shape

(31780, 31)

In [6]:
import pandas as pd

# Load full Kaggle dataset
df = pd.read_csv("creditcard.csv")

# Select demo rows (e.g., 20 legit + 10 fraud)
demo_rows = pd.concat([
    df[df['Class'] == 0].sample(n=20, random_state=42),
    df[df['Class'] == 1].sample(n=10, random_state=42)
])

# Save demo CSV for testing
demo_rows.to_csv("demo_transactions.csv", index=False)

# Remove demo rows from training data
df_train = df.drop(demo_rows.index)

# Now df_train can be used to train your model

In [7]:
y = data["Class"]                # Target
X = data.drop("Class", axis=1)   # Features

In [8]:
y = y.dropna()
X = X.loc[y.index]  # align features with cleaned y

In [9]:
y.isna().sum()

np.int64(0)

In [10]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, Ytrain, Ytest = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [11]:
print(y.value_counts(normalize=True))

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

In [12]:
#Imbalance is there,Resampling is needed
from imblearn.over_sampling import SMOTE

sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(Xtrain, Ytrain)

In [13]:
#Checking for balance
import pandas as pd

# Before resampling
print("Original class distribution:")
print(pd.Series(Ytrain).value_counts())

# After resampling
print("Resampled class distribution:")
print(pd.Series(y_res).value_counts())

Original class distribution:
Class
0    227451
1       394
Name: count, dtype: int64
Resampled class distribution:
Class
0    227451
1    227451
Name: count, dtype: int64

In [29]:
print(data.shape)

(31780, 31)

In [30]:
print("Before SMOTE:", Xtrain.shape)
print("After SMOTE:", X_res.shape)

Before SMOTE: (25423, 30)
After SMOTE: (50682, 30)

In [14]:

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Load Kaggle dataset (already has Time, V1â€“V28, Amount, Class)
df = pd.read_csv("creditcard.csv")

# 2. Features and target
X = df.drop("Class", axis=1)
y = df["Class"]

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Train RandomForest directly on Kaggle features
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    n_jobs=-1,
    random_state=42,
    class_weight="balanced"   # important for imbalanced fraud data
)
model.fit(X_train, y_train)

# 5. Evaluate
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# 6. Save trained model
joblib.dump(model, "fraud_rf_model.pkl")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.82      0.83      0.82        98

    accuracy                           1.00     56962
   macro avg       0.91      0.91      0.91     56962
weighted avg       1.00      1.00      1.00     56962

[[56846    18]
 [   17    81]]
âœ… Model trained and saved as fraud_rf_model.pkl

In [15]:
import joblib

# Load trained model
model = joblib.load("fraud_rf_model.pkl")

# Load demo CSV
demo_df = pd.read_csv("demo_transactions.csv")
X_demo = demo_df.drop("Class", axis=1)
y_demo = demo_df["Class"]

# Predict
y_pred = model.predict(X_demo)

# Compare
demo_df['Predicted'] = y_pred
print(demo_df[['Time','Amount','Class','Predicted']])

        Time  Amount  Class  Predicted
0    82450.0    0.76      0          0
1    50554.0    4.18      0          0
2    55125.0   15.00      0          0
3   116572.0   57.00      0          0
4    90434.0    0.00      0          0
5    39411.0   43.89      0          0
6   100409.0   49.83      0          0
7    31054.0   35.00      0          0
8   111675.0  219.00      0          0
9    18895.0   11.85      0          0
10   42330.0   35.90      0          0
11  154024.0    1.98      0          0
12   81853.0  108.22      0          0
13   56703.0   56.19      0          0
14  128733.0    9.99      0          0
15  154352.0   13.99      0          0
16   44022.0  435.70      0          0
17   52222.0   70.65      0          0
18   42510.0   24.09      0          0
19  142570.0   17.82      0          0
20   28692.0   99.99      1          1
21   21662.0    1.00      1          1
22   85285.0    0.00      1          1
23   91075.0   38.76      1          1
24   26585.0   99.99      1          1
25   55760.0  311.91      1          1
26   12093.0    0.00      1          1
27   41194.0    1.52      1          1
28  155662.0    0.77      1          1
29  101597.0  147.87      1          1